### ISSUE TITLE
Update pypi package with latest google closure compiler: October 23, 2017 (v20171023)

### ISSUE THREAD

**Issue by Morabaraba** [miracle2k/python-closure#15]
Hi,

What unit of work or testing needs to get done to update the [pypi package](https://pypi.python.org/pypi/closure) to the [latest google closure compiler jar][compiler-latest]: October 23, 2017 ([v20171023])?

Currently `java -jar closure.jar --version` returns v20161201 and I would like the closure python package to keep up to date.

If I can assist let me know.

Thanks,

[v20171023]: https://github.com/google/closure-compiler/wiki/Releases#october-23-2017-v20171023
[compiler-latest]: https://dl.google.com/closure-compiler/compiler-latest.zip

**Comment by miracle2k** [comment]
I published a new version.

**Comment by Morabaraba** [comment]
Heads up you now need Java 8:

```sh
(venv) :~/workspace/(master) $ java -jar venv/lib/python3.6/site-packages/closure/closure.jar --version
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
```

Was on OpenJDK7. Bumped it to the [Oracle JDK8](https://askubuntu.com/a/464894) and it works. OpenJDK8 should work as well.

Thanks! 👍
